### ISSUE TITLE
Compilation from Source fails

### ISSUE THREAD

**Issue by ForkedInTime** [k4yt3x/video2x#1329]
**Describe the bug**
Compilation of video2x-qt6 on Linux fails 

**To Reproduce**

1. download video2x-qt6 repo
2. cd video2x-qt6  && mkdir /build
3. cd build/
4. cmake ..
5. make -j$(nproc)

**Expected behavior**
Compilation should build ok ..stops at 97%

**Actual behavior**
Failed compilation with error:
 95%] Building CXX object CMakeFiles/video2x.dir/tools/video2x/src/video2x.cpp.o
[ 97%] Building CXX object CMakeFiles/video2x.dir/tools/video2x/src/vulkan_utils.cpp.o
/home/yetipaw/MyApps/Repos/video2x-qt6/third_party/video2x/tools/video2x/src/validators.cpp: In function ‘void validate_anime4k_shader_name(const video2x::fsutils::StringType&)’:
/home/yetipaw/MyApps/Repos/video2x-qt6/third_party/video2x/tools/video2x/src/validators.cpp:21:9: error: exception handling disabled, use ‘-fexceptions’ to enable
   21 |         );
      |         ^
/home/yetipaw/MyApps/Repos/video2x-qt6/third_party/video2x/tools/video2x/src/argparse.cpp: In function ‘int parse_args(int, char**, Arguments&, video2x::processors::ProcessorConfig&, video2x::encoder::EncoderConfig&)’:
/home/yetipaw/MyApps/Repos/video2x-qt6/third_party/video2x/tools/video2x/src/argparse.cpp:470:31: error: exception handling disabled, use ‘-fexceptions’ to enable
  470 |     } catch (const po::error &e) {

![Image](https://github.com/user-attachments/assets/1cdf7d42-b670-400a-b7a7-7be28a41769b)

**Screenshots**

**Environment:**

- OS: PoPOS (Ubuntu 22.04)
- GPU: NVIDIA GeForce RTX 3090 Ti
- Video2X Version: 6.4.0

[video2x-qt6-error-log.txt](https://github.com/user-attachments/files/18700409/video2x-qt6-error-log.txt)

**Full command**
If applicable, add the full command you used to run the program.

**Additional context**

**Comment by k4yt3x** [comment]
First of all the FFmpeg on Ubuntu 22 is too old and libplacebo won't run. I think you'll have a better chance using the AppImage.

For the full process required to build on Ubuntu 22, take a look at the `ubuntu22` examples in the `.justfile`:

https://github.com/k4yt3x/video2x/blob/3e987b9693650ac71afc643742ee7424d2ef4519/.justfile#L132-L158

Still, I don't recommend building it on Ubuntu 22. Use at least 24.

**Comment by ForkedInTime** [comment]
Thank you for this. The AppImage also does not work on Ubuntu 22.04 (glibc is too olde). Switching to 24.10.
